module.exports = [
  {
    "city": "Athens",
    "lat": "37.9842",
    "lng": "23.7281",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "primary",
    "population": "664046",
    "population_proper": "664046"
  },
  {
    "city": "Thessaloníki",
    "lat": "40.6403",
    "lng": "22.9356",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "admin",
    "population": "315196",
    "population_proper": "315196"
  },
  {
    "city": "Pátra",
    "lat": "38.2500",
    "lng": "21.7333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "admin",
    "population": "167446",
    "population_proper": "167446"
  },
  {
    "city": "Piraeus",
    "lat": "37.9430",
    "lng": "23.6469",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "163688",
    "population_proper": "163688"
  },
  {
    "city": "Lárisa",
    "lat": "39.6369",
    "lng": "22.4176",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "admin",
    "population": "144651",
    "population_proper": "144651"
  },
  {
    "city": "Irákleio",
    "lat": "35.3403",
    "lng": "25.1344",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "admin",
    "population": "140730",
    "population_proper": "140730"
  },
  {
    "city": "Peristéri",
    "lat": "38.0167",
    "lng": "23.6833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "139981",
    "population_proper": "139981"
  },
  {
    "city": "Kallithéa",
    "lat": "37.9500",
    "lng": "23.7000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "100641",
    "population_proper": "100641"
  },
  {
    "city": "Níkaia",
    "lat": "37.9667",
    "lng": "23.6333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "89380",
    "population_proper": "89380"
  },
  {
    "city": "Glyfáda",
    "lat": "37.8800",
    "lng": "23.7533",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "87305",
    "population_proper": "87305"
  },
  {
    "city": "Vólos",
    "lat": "39.3611",
    "lng": "22.9425",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "86046",
    "population_proper": "86046"
  },
  {
    "city": "Chaniá",
    "lat": "35.5173",
    "lng": "24.0195",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "minor",
    "population": "78728",
    "population_proper": "54565"
  },
  {
    "city": "Chalándri",
    "lat": "38.0167",
    "lng": "23.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "74192",
    "population_proper": "74192"
  },
  {
    "city": "Kalamáta",
    "lat": "37.0389",
    "lng": "22.1142",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "71823",
    "population_proper": "51108"
  },
  {
    "city": "Néa Ionía",
    "lat": "38.0333",
    "lng": "23.7500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "67134",
    "population_proper": "67134"
  },
  {
    "city": "Ioánnina",
    "lat": "39.6636",
    "lng": "20.8522",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "admin",
    "population": "65574",
    "population_proper": "65574"
  },
  {
    "city": "Palaió Fáliro",
    "lat": "37.9320",
    "lng": "23.7003",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "64021",
    "population_proper": "64021"
  },
  {
    "city": "Tríkala",
    "lat": "39.5550",
    "lng": "21.7683",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "61653",
    "population_proper": "61653"
  },
  {
    "city": "Výronas",
    "lat": "37.9556",
    "lng": "23.7600",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "61308",
    "population_proper": "61308"
  },
  {
    "city": "Agía Paraskeví",
    "lat": "38.0053",
    "lng": "23.8208",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "59704",
    "population_proper": "59704"
  },
  {
    "city": "Galátsi",
    "lat": "38.0167",
    "lng": "23.7500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "59345",
    "population_proper": "59345"
  },
  {
    "city": "Kavála",
    "lat": "40.9350",
    "lng": "24.4150",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "59240",
    "population_proper": "52950"
  },
  {
    "city": "Chalkída",
    "lat": "38.4625",
    "lng": "23.5950",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "59125",
    "population_proper": "59125"
  },
  {
    "city": "Sérres",
    "lat": "41.0833",
    "lng": "23.5500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "58287",
    "population_proper": "58287"
  },
  {
    "city": "Alexandroúpoli",
    "lat": "40.8500",
    "lng": "25.8667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "57812",
    "population_proper": "57812"
  },
  {
    "city": "Ródos",
    "lat": "36.4412",
    "lng": "28.2225",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "56969",
    "population_proper": "56128"
  },
  {
    "city": "Xánthi",
    "lat": "41.1333",
    "lng": "24.8833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "56122",
    "population_proper": "56122"
  },
  {
    "city": "Kateríni",
    "lat": "40.2667",
    "lng": "22.5000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "55997",
    "population_proper": "55997"
  },
  {
    "city": "Lamía",
    "lat": "38.8972",
    "lng": "22.4311",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "admin",
    "population": "52006",
    "population_proper": "52006"
  },
  {
    "city": "Komotiní",
    "lat": "41.1167",
    "lng": "25.4000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "admin",
    "population": "50990",
    "population_proper": "50990"
  },
  {
    "city": "Agrínio",
    "lat": "38.6167",
    "lng": "21.4000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "46899",
    "population_proper": "46899"
  },
  {
    "city": "Chaïdári",
    "lat": "38.0167",
    "lng": "23.6500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "45642",
    "population_proper": "45642"
  },
  {
    "city": "Dráma",
    "lat": "41.1514",
    "lng": "24.1392",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "44823",
    "population_proper": "44823"
  },
  {
    "city": "Véroia",
    "lat": "40.5203",
    "lng": "22.2019",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "43158",
    "population_proper": "43158"
  },
  {
    "city": "Kozáni",
    "lat": "40.3007",
    "lng": "21.7890",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "admin",
    "population": "41066",
    "population_proper": "41066"
  },
  {
    "city": "Kardítsa",
    "lat": "39.3647",
    "lng": "21.9219",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "38554",
    "population_proper": "38554"
  },
  {
    "city": "Réthymno",
    "lat": "35.3689",
    "lng": "24.4739",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "minor",
    "population": "32468",
    "population_proper": "32468"
  },
  {
    "city": "Trípoli",
    "lat": "37.5083",
    "lng": "22.3750",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "admin",
    "population": "30866",
    "population_proper": "30866"
  },
  {
    "city": "Vrilíssia",
    "lat": "38.0391",
    "lng": "23.8378",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "30741",
    "population_proper": "30741"
  },
  {
    "city": "Kórinthos",
    "lat": "37.9333",
    "lng": "22.9333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "30176",
    "population_proper": "30176"
  },
  {
    "city": "Giannitsá",
    "lat": "40.7962",
    "lng": "22.4145",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "29789",
    "population_proper": "29789"
  },
  {
    "city": "Mytilíni",
    "lat": "39.1114",
    "lng": "26.5621",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "admin",
    "population": "29328",
    "population_proper": "28322"
  },
  {
    "city": "Chíos",
    "lat": "38.3725",
    "lng": "26.1375",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "minor",
    "population": "26850",
    "population_proper": "26850"
  },
  {
    "city": "Kaisarianí",
    "lat": "37.9633",
    "lng": "23.7653",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "26370",
    "population_proper": "26370"
  },
  {
    "city": "Néa Filadélfeia",
    "lat": "38.0350",
    "lng": "23.7381",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "25734",
    "population_proper": "25734"
  },
  {
    "city": "Salamína",
    "lat": "37.9333",
    "lng": "23.5000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "25370",
    "population_proper": "25370"
  },
  {
    "city": "Elefsína",
    "lat": "38.0414",
    "lng": "23.5453",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "24910",
    "population_proper": "24910"
  },
  {
    "city": "Kérkyra",
    "lat": "39.6239",
    "lng": "19.9214",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "admin",
    "population": "24838",
    "population_proper": "24838"
  },
  {
    "city": "Pýrgos",
    "lat": "37.6667",
    "lng": "21.4333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "24359",
    "population_proper": "24359"
  },
  {
    "city": "Mégara",
    "lat": "38.0000",
    "lng": "23.3333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "23456",
    "population_proper": "23456"
  },
  {
    "city": "Kilkís",
    "lat": "40.9954",
    "lng": "22.8765",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "22914",
    "population_proper": "22914"
  },
  {
    "city": "Thebes",
    "lat": "38.3242",
    "lng": "23.3236",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "22883",
    "population_proper": "22883"
  },
  {
    "city": "Lefkáda",
    "lat": "38.7178",
    "lng": "20.6439",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "minor",
    "population": "22652",
    "population_proper": "22652"
  },
  {
    "city": "Áno Sýros",
    "lat": "37.4500",
    "lng": "24.9000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "21507",
    "population_proper": "21507"
  },
  {
    "city": "Péfki",
    "lat": "38.0667",
    "lng": "23.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "21415",
    "population_proper": "21415"
  },
  {
    "city": "Livadeiá",
    "lat": "38.4361",
    "lng": "22.8750",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "21379",
    "population_proper": "21379"
  },
  {
    "city": "Kos",
    "lat": "36.8153",
    "lng": "27.1103",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "19244",
    "population_proper": "18691"
  },
  {
    "city": "Préveza",
    "lat": "38.9500",
    "lng": "20.7500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "minor",
    "population": "19042",
    "population_proper": "19042"
  },
  {
    "city": "Orestiáda",
    "lat": "41.5000",
    "lng": "26.5333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "18426",
    "population_proper": "18426"
  },
  {
    "city": "Spárti",
    "lat": "37.0819",
    "lng": "22.4236",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "16187",
    "population_proper": "15497"
  },
  {
    "city": "Thérmi",
    "lat": "40.5472",
    "lng": "23.0197",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "16004",
    "population_proper": "16004"
  },
  {
    "city": "Alexándreia",
    "lat": "40.6283",
    "lng": "22.4454",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "14821",
    "population_proper": "14821"
  },
  {
    "city": "Paianía",
    "lat": "37.9500",
    "lng": "23.8500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "14595",
    "population_proper": "14595"
  },
  {
    "city": "Náfplio",
    "lat": "37.5667",
    "lng": "22.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "14203",
    "population_proper": "14203"
  },
  {
    "city": "Náfpaktos",
    "lat": "38.3917",
    "lng": "21.8275",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "13415",
    "population_proper": "13415"
  },
  {
    "city": "Kastoriá",
    "lat": "40.5181",
    "lng": "21.2688",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "minor",
    "population": "13387",
    "population_proper": "13387"
  },
  {
    "city": "Néa Alikarnassós",
    "lat": "35.3286",
    "lng": "25.1644",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "12925",
    "population_proper": "12925"
  },
  {
    "city": "Kálymnos",
    "lat": "36.9512",
    "lng": "26.9832",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "12324",
    "population_proper": "12324"
  },
  {
    "city": "Ermoúpoli",
    "lat": "37.4504",
    "lng": "24.9333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "admin",
    "population": "12260",
    "population_proper": "12260"
  },
  {
    "city": "Týrnavos",
    "lat": "39.7353",
    "lng": "22.2869",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "11069",
    "population_proper": "11069"
  },
  {
    "city": "Diavatá",
    "lat": "40.6883",
    "lng": "22.8583",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "9890",
    "population_proper": "9890"
  },
  {
    "city": "Kiáto",
    "lat": "38.0117",
    "lng": "22.7467",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "9812",
    "population_proper": "9812"
  },
  {
    "city": "Anatolí",
    "lat": "39.6386",
    "lng": "20.8661",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "",
    "population": "9798",
    "population_proper": "9798"
  },
  {
    "city": "Argostóli",
    "lat": "38.1739",
    "lng": "20.4883",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "minor",
    "population": "9748",
    "population_proper": "9748"
  },
  {
    "city": "Lykóvrysi",
    "lat": "38.0667",
    "lng": "23.7833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "9738",
    "population_proper": "9738"
  },
  {
    "city": "Pórto Ráfti",
    "lat": "37.8844",
    "lng": "24.0125",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "9686",
    "population_proper": "9686"
  },
  {
    "city": "Psychikó",
    "lat": "38.0180",
    "lng": "23.7804",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "9529",
    "population_proper": "9529"
  },
  {
    "city": "Néa Artáki",
    "lat": "38.5167",
    "lng": "23.6333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "",
    "population": "9489",
    "population_proper": "9489"
  },
  {
    "city": "Zefýri",
    "lat": "38.0667",
    "lng": "23.7167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "9454",
    "population_proper": "9454"
  },
  {
    "city": "Siteía",
    "lat": "35.2000",
    "lng": "26.1000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "minor",
    "population": "9348",
    "population_proper": "9348"
  },
  {
    "city": "Néa Moudaniá",
    "lat": "40.2386",
    "lng": "23.2814",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "9342",
    "population_proper": "9342"
  },
  {
    "city": "Fársala",
    "lat": "39.2833",
    "lng": "22.3833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "9298",
    "population_proper": "9298"
  },
  {
    "city": "Síndos",
    "lat": "40.6667",
    "lng": "22.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "9289",
    "population_proper": "9289"
  },
  {
    "city": "Didymóteicho",
    "lat": "41.3500",
    "lng": "26.5000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "9263",
    "population_proper": "9263"
  },
  {
    "city": "Spáta",
    "lat": "37.9667",
    "lng": "23.9167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "9198",
    "population_proper": "9198"
  },
  {
    "city": "Epanomí",
    "lat": "40.4261",
    "lng": "22.9281",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "8979",
    "population_proper": "8979"
  },
  {
    "city": "Chrysoúpoli",
    "lat": "40.9833",
    "lng": "24.7000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "8885",
    "population_proper": "8885"
  },
  {
    "city": "Néa Péramos",
    "lat": "38.0000",
    "lng": "23.4167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "8333",
    "population_proper": "8333"
  },
  {
    "city": "Kalampáka",
    "lat": "39.7044",
    "lng": "21.6269",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "8330",
    "population_proper": "8330"
  },
  {
    "city": "Almyrós",
    "lat": "39.1803",
    "lng": "22.7606",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "7955",
    "population_proper": "7955"
  },
  {
    "city": "Koufália",
    "lat": "40.7792",
    "lng": "22.5767",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "7850",
    "population_proper": "7850"
  },
  {
    "city": "Giánnouli",
    "lat": "39.6672",
    "lng": "22.3958",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "",
    "population": "7847",
    "population_proper": "7847"
  },
  {
    "city": "Lagkadás",
    "lat": "40.7500",
    "lng": "23.0667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "7764",
    "population_proper": "7764"
  },
  {
    "city": "Mourniés",
    "lat": "35.4850",
    "lng": "24.0130",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "7553",
    "population_proper": "7553"
  },
  {
    "city": "Elassóna",
    "lat": "39.8947",
    "lng": "22.1886",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "7338",
    "population_proper": "7338"
  },
  {
    "city": "Chalástra",
    "lat": "40.6267",
    "lng": "22.7322",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "7270",
    "population_proper": "7270"
  },
  {
    "city": "Néa Kallikráteia",
    "lat": "40.3139",
    "lng": "23.0633",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "7238",
    "population_proper": "7238"
  },
  {
    "city": "Karpenísi",
    "lat": "38.9203",
    "lng": "21.7833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "7183",
    "population_proper": "7183"
  },
  {
    "city": "Marathónas",
    "lat": "38.1550",
    "lng": "23.9636",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "7170",
    "population_proper": "7170"
  },
  {
    "city": "Lávrio",
    "lat": "37.7000",
    "lng": "24.0500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "7078",
    "population_proper": "7078"
  },
  {
    "city": "Polýkastro",
    "lat": "40.9954",
    "lng": "22.5714",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "7064",
    "population_proper": "7064"
  },
  {
    "city": "Litóchoro",
    "lat": "40.1028",
    "lng": "22.5069",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "6995",
    "population_proper": "6995"
  },
  {
    "city": "Aígina",
    "lat": "37.7467",
    "lng": "23.4275",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "6867",
    "population_proper": "6867"
  },
  {
    "city": "Néo Karlovási",
    "lat": "37.7917",
    "lng": "26.7051",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "",
    "population": "6708",
    "population_proper": "6708"
  },
  {
    "city": "Káto Achaḯa",
    "lat": "38.1500",
    "lng": "21.5500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "6618",
    "population_proper": "6618"
  },
  {
    "city": "Aridaía",
    "lat": "40.9750",
    "lng": "22.0583",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "6561",
    "population_proper": "6561"
  },
  {
    "city": "Soúda",
    "lat": "35.4833",
    "lng": "24.0667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "6358",
    "population_proper": "6358"
  },
  {
    "city": "Kounoupidianá",
    "lat": "35.5360",
    "lng": "24.0760",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "6334",
    "population_proper": "6334"
  },
  {
    "city": "Anávyssos",
    "lat": "37.7333",
    "lng": "23.9500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "6202",
    "population_proper": "6202"
  },
  {
    "city": "Polýgyros",
    "lat": "40.3783",
    "lng": "23.4453",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "6121",
    "population_proper": "6121"
  },
  {
    "city": "Messíni",
    "lat": "37.0500",
    "lng": "22.0000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "6065",
    "population_proper": "6065"
  },
  {
    "city": "Néoi Epivátes",
    "lat": "40.5010",
    "lng": "22.9090",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "5984",
    "population_proper": "5984"
  },
  {
    "city": "Filiatrá",
    "lat": "37.1572",
    "lng": "21.5858",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "",
    "population": "5969",
    "population_proper": "5969"
  },
  {
    "city": "Psachná",
    "lat": "38.5828",
    "lng": "23.6328",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "5827",
    "population_proper": "5827"
  },
  {
    "city": "Megalópoli",
    "lat": "37.4000",
    "lng": "22.1333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "5748",
    "population_proper": "5748"
  },
  {
    "city": "Mýrina",
    "lat": "39.8797",
    "lng": "25.0742",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "minor",
    "population": "5711",
    "population_proper": "5711"
  },
  {
    "city": "Diónysos",
    "lat": "38.1000",
    "lng": "23.8667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "5651",
    "population_proper": "5651"
  },
  {
    "city": "Nerokoúros",
    "lat": "35.4758",
    "lng": "24.0383",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "5531",
    "population_proper": "5531"
  },
  {
    "city": "Xylókastro",
    "lat": "38.0667",
    "lng": "22.6333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "5500",
    "population_proper": "5500"
  },
  {
    "city": "Fílyro",
    "lat": "40.6911",
    "lng": "23.0042",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "5495",
    "population_proper": "5495"
  },
  {
    "city": "Siátista",
    "lat": "40.2564",
    "lng": "21.5522",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "minor",
    "population": "5490",
    "population_proper": "5490"
  },
  {
    "city": "Féres",
    "lat": "40.8933",
    "lng": "26.1739",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "5457",
    "population_proper": "5457"
  },
  {
    "city": "Skýdra",
    "lat": "40.7667",
    "lng": "22.1500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "5406",
    "population_proper": "5406"
  },
  {
    "city": "Archángelos",
    "lat": "36.2167",
    "lng": "28.1167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "",
    "population": "5384",
    "population_proper": "5384"
  },
  {
    "city": "Kremastí",
    "lat": "36.4105",
    "lng": "28.1191",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "",
    "population": "5363",
    "population_proper": "5363"
  },
  {
    "city": "Vrontádos",
    "lat": "38.4167",
    "lng": "26.1333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "",
    "population": "5323",
    "population_proper": "5323"
  },
  {
    "city": "Tympáki",
    "lat": "35.0719",
    "lng": "24.7683",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "5285",
    "population_proper": "5285"
  },
  {
    "city": "Orchomenós",
    "lat": "38.4933",
    "lng": "22.9749",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "5238",
    "population_proper": "5238"
  },
  {
    "city": "Agriá",
    "lat": "39.3400",
    "lng": "23.0133",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "",
    "population": "5191",
    "population_proper": "5191"
  },
  {
    "city": "Néa Anchiálos",
    "lat": "39.2667",
    "lng": "22.8167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "",
    "population": "5132",
    "population_proper": "5132"
  },
  {
    "city": "Kyparissía",
    "lat": "37.2333",
    "lng": "21.6667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "5131",
    "population_proper": "5131"
  },
  {
    "city": "Gargaliánoi",
    "lat": "37.0667",
    "lng": "21.6333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "",
    "population": "5007",
    "population_proper": "5007"
  },
  {
    "city": "Nigríta",
    "lat": "40.9133",
    "lng": "23.5014",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "4947",
    "population_proper": "4947"
  },
  {
    "city": "Skiáthos",
    "lat": "39.1652",
    "lng": "23.4895",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "4883",
    "population_proper": "4883"
  },
  {
    "city": "Chortiátis",
    "lat": "40.6083",
    "lng": "23.1028",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "4873",
    "population_proper": "4873"
  },
  {
    "city": "Alivéri",
    "lat": "38.4083",
    "lng": "24.0417",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "4827",
    "population_proper": "4827"
  },
  {
    "city": "Tínos",
    "lat": "37.5377",
    "lng": "25.1611",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "4762",
    "population_proper": "4762"
  },
  {
    "city": "Magoúla",
    "lat": "38.0833",
    "lng": "23.5167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "4735",
    "population_proper": "4735"
  },
  {
    "city": "Stafidókampos",
    "lat": "37.8933",
    "lng": "21.2933",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "4716",
    "population_proper": "4716"
  },
  {
    "city": "Ampelákia",
    "lat": "37.9500",
    "lng": "23.5167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "4710",
    "population_proper": "4710"
  },
  {
    "city": "Vónitsa",
    "lat": "38.9153",
    "lng": "20.8911",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "4703",
    "population_proper": "4703"
  },
  {
    "city": "Filippiáda",
    "lat": "39.2028",
    "lng": "20.8842",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "minor",
    "population": "4619",
    "population_proper": "4619"
  },
  {
    "city": "Alíartos",
    "lat": "38.3667",
    "lng": "23.1000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "4402",
    "population_proper": "4402"
  },
  {
    "city": "Zevgolatió",
    "lat": "37.9333",
    "lng": "22.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "",
    "population": "4363",
    "population_proper": "4363"
  },
  {
    "city": "Itéa",
    "lat": "38.4333",
    "lng": "22.4333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "",
    "population": "4362",
    "population_proper": "4362"
  },
  {
    "city": "Istiaía",
    "lat": "38.9500",
    "lng": "23.1500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "4339",
    "population_proper": "4339"
  },
  {
    "city": "Arkalochóri",
    "lat": "35.1500",
    "lng": "25.2667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "4313",
    "population_proper": "4313"
  },
  {
    "city": "Gýtheio",
    "lat": "36.7617",
    "lng": "22.5661",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "4279",
    "population_proper": "4279"
  },
  {
    "city": "Néa Magnisía",
    "lat": "40.6878",
    "lng": "22.8458",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "4266",
    "population_proper": "4266"
  },
  {
    "city": "Kíssamos",
    "lat": "35.4833",
    "lng": "23.6500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "minor",
    "population": "4236",
    "population_proper": "4236"
  },
  {
    "city": "Vouliagméni",
    "lat": "37.8000",
    "lng": "23.7833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "4180",
    "population_proper": "4180"
  },
  {
    "city": "Aigínio",
    "lat": "40.5022",
    "lng": "22.5422",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "4153",
    "population_proper": "4153"
  },
  {
    "city": "Kítsi",
    "lat": "37.8456",
    "lng": "23.8267",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "4091",
    "population_proper": "4091"
  },
  {
    "city": "Schimatári",
    "lat": "38.3500",
    "lng": "23.5833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "4035",
    "population_proper": "4035"
  },
  {
    "city": "Aitolikó",
    "lat": "38.4369",
    "lng": "21.3536",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "4012",
    "population_proper": "4012"
  },
  {
    "city": "Kranídi",
    "lat": "37.3750",
    "lng": "23.1583",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "4006",
    "population_proper": "4006"
  },
  {
    "city": "Spétses",
    "lat": "37.2591",
    "lng": "23.1364",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "minor",
    "population": "4001",
    "population_proper": "4001"
  },
  {
    "city": "Andravída",
    "lat": "37.9058",
    "lng": "21.2667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "3981",
    "population_proper": "3981"
  },
  {
    "city": "Katsikás",
    "lat": "39.6228",
    "lng": "20.8875",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "",
    "population": "3885",
    "population_proper": "3885"
  },
  {
    "city": "Néa Raidestós",
    "lat": "40.5239",
    "lng": "23.0508",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3869",
    "population_proper": "3869"
  },
  {
    "city": "Neméa",
    "lat": "37.8167",
    "lng": "22.6667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "3853",
    "population_proper": "3853"
  },
  {
    "city": "Potamós",
    "lat": "39.6239",
    "lng": "19.8792",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "",
    "population": "3840",
    "population_proper": "3840"
  },
  {
    "city": "Souflí",
    "lat": "41.1942",
    "lng": "26.3023",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "3837",
    "population_proper": "3837"
  },
  {
    "city": "Amfilochía",
    "lat": "38.8592",
    "lng": "21.1758",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "3827",
    "population_proper": "3827"
  },
  {
    "city": "Mýkonos",
    "lat": "37.4453",
    "lng": "25.3287",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "3783",
    "population_proper": "3783"
  },
  {
    "city": "Vasiliká",
    "lat": "40.4800",
    "lng": "23.1367",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3762",
    "population_proper": "3762"
  },
  {
    "city": "Leonídio",
    "lat": "37.1667",
    "lng": "22.8500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "3761",
    "population_proper": "3761"
  },
  {
    "city": "Lixoúri",
    "lat": "38.2000",
    "lng": "20.4333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "",
    "population": "3752",
    "population_proper": "3752"
  },
  {
    "city": "Leptokaryá",
    "lat": "40.0603",
    "lng": "22.5612",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3700",
    "population_proper": "3700"
  },
  {
    "city": "Stavrós",
    "lat": "40.6642",
    "lng": "23.6961",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "3672",
    "population_proper": "3672"
  },
  {
    "city": "Amýntaio",
    "lat": "40.6897",
    "lng": "21.6797",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "minor",
    "population": "3671",
    "population_proper": "3671"
  },
  {
    "city": "Kimméria",
    "lat": "41.1475",
    "lng": "24.9388",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "3644",
    "population_proper": "3644"
  },
  {
    "city": "Gouménissa",
    "lat": "40.9481",
    "lng": "22.4519",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3609",
    "population_proper": "3609"
  },
  {
    "city": "Vartholomió",
    "lat": "37.8622",
    "lng": "21.2058",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "3603",
    "population_proper": "3603"
  },
  {
    "city": "Lagyná",
    "lat": "40.7233",
    "lng": "23.0050",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3591",
    "population_proper": "3591"
  },
  {
    "city": "Prosotsáni",
    "lat": "41.1786",
    "lng": "23.9722",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "3553",
    "population_proper": "3553"
  },
  {
    "city": "Néa Péramos",
    "lat": "40.8389",
    "lng": "24.3036",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "3514",
    "population_proper": "3514"
  },
  {
    "city": "Korinós",
    "lat": "40.3167",
    "lng": "22.5833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3487",
    "population_proper": "3487"
  },
  {
    "city": "Krinídes",
    "lat": "41.0131",
    "lng": "24.2950",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "3365",
    "population_proper": "3365"
  },
  {
    "city": "Velventós",
    "lat": "40.2547",
    "lng": "22.0742",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "",
    "population": "3360",
    "population_proper": "3360"
  },
  {
    "city": "Kapandríti",
    "lat": "38.2167",
    "lng": "23.8833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "3359",
    "population_proper": "3359"
  },
  {
    "city": "Sápes",
    "lat": "41.0333",
    "lng": "25.7000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "3351",
    "population_proper": "3351"
  },
  {
    "city": "Vracháti",
    "lat": "37.9500",
    "lng": "22.8000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "",
    "population": "3338",
    "population_proper": "3338"
  },
  {
    "city": "Lití",
    "lat": "40.7447",
    "lng": "22.9781",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3302",
    "population_proper": "3302"
  },
  {
    "city": "Ierissós",
    "lat": "40.3983",
    "lng": "23.8783",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "3266",
    "population_proper": "3266"
  },
  {
    "city": "Thásos",
    "lat": "40.7781",
    "lng": "24.7094",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "3234",
    "population_proper": "3234"
  },
  {
    "city": "Itháki",
    "lat": "38.4167",
    "lng": "20.6667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "minor",
    "population": "3231",
    "population_proper": "3231"
  },
  {
    "city": "Mália",
    "lat": "35.2836",
    "lng": "25.4625",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kríti",
    "capital": "",
    "population": "3224",
    "population_proper": "3224"
  },
  {
    "city": "Néos Marmarás",
    "lat": "40.0967",
    "lng": "23.7831",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3158",
    "population_proper": "3158"
  },
  {
    "city": "Zacháro",
    "lat": "37.4861",
    "lng": "21.6494",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "3145",
    "population_proper": "3145"
  },
  {
    "city": "Kallithéa",
    "lat": "40.2750",
    "lng": "22.5750",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3134",
    "population_proper": "3134"
  },
  {
    "city": "Melíki",
    "lat": "40.5167",
    "lng": "22.4000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3116",
    "population_proper": "3116"
  },
  {
    "city": "Kalampáki",
    "lat": "41.0500",
    "lng": "24.1833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "minor",
    "population": "3110",
    "population_proper": "3110"
  },
  {
    "city": "Néa Tríglia",
    "lat": "40.3061",
    "lng": "23.2086",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3102",
    "population_proper": "3102"
  },
  {
    "city": "Sochós",
    "lat": "40.8164",
    "lng": "23.3542",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3094",
    "population_proper": "3094"
  },
  {
    "city": "Skópelos",
    "lat": "39.1167",
    "lng": "23.7167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "3090",
    "population_proper": "3090"
  },
  {
    "city": "Skála",
    "lat": "36.8525",
    "lng": "22.6661",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "minor",
    "population": "3067",
    "population_proper": "3067"
  },
  {
    "city": "Ntráfi",
    "lat": "38.0333",
    "lng": "23.9000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "3055",
    "population_proper": "3055"
  },
  {
    "city": "Maniákoi",
    "lat": "40.5019",
    "lng": "21.2447",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Makedonía",
    "capital": "",
    "population": "3055",
    "population_proper": "3055"
  },
  {
    "city": "Néa Mesimvría",
    "lat": "40.7517",
    "lng": "22.7692",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "3050",
    "population_proper": "3050"
  },
  {
    "city": "Velestíno",
    "lat": "39.3817",
    "lng": "22.7450",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Thessalía",
    "capital": "minor",
    "population": "3044",
    "population_proper": "3044"
  },
  {
    "city": "Plomári",
    "lat": "38.9833",
    "lng": "26.3667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Voreío Aigaío",
    "capital": "",
    "population": "2996",
    "population_proper": "2996"
  },
  {
    "city": "Ormýlia",
    "lat": "40.2944",
    "lng": "23.5433",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "2979",
    "population_proper": "2979"
  },
  {
    "city": "Néo Rýsi",
    "lat": "40.4961",
    "lng": "22.9881",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "2952",
    "population_proper": "2952"
  },
  {
    "city": "Kónitsa",
    "lat": "40.0417",
    "lng": "20.7450",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ípeiros",
    "capital": "minor",
    "population": "2942",
    "population_proper": "2942"
  },
  {
    "city": "Lefkímmi",
    "lat": "39.4167",
    "lng": "20.0667",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Ionía Nísia",
    "capital": "",
    "population": "2935",
    "population_proper": "2935"
  },
  {
    "city": "Panaitólio",
    "lat": "38.5833",
    "lng": "21.4461",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "2935",
    "population_proper": "2935"
  },
  {
    "city": "Saronída",
    "lat": "37.7333",
    "lng": "23.9000",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "2932",
    "population_proper": "2932"
  },
  {
    "city": "Axioúpoli",
    "lat": "40.9858",
    "lng": "22.5417",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "2897",
    "population_proper": "2897"
  },
  {
    "city": "Erythrés",
    "lat": "38.2167",
    "lng": "23.3167",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "2862",
    "population_proper": "2862"
  },
  {
    "city": "Asproválta",
    "lat": "40.7247",
    "lng": "23.7056",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "2838",
    "population_proper": "2838"
  },
  {
    "city": "Katochí",
    "lat": "38.4142",
    "lng": "21.2542",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "2829",
    "population_proper": "2829"
  },
  {
    "city": "Neochóri",
    "lat": "38.4083",
    "lng": "21.2750",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "",
    "population": "2827",
    "population_proper": "2827"
  },
  {
    "city": "Kolindrós",
    "lat": "40.4783",
    "lng": "22.4861",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "",
    "population": "2822",
    "population_proper": "2822"
  },
  {
    "city": "Néa Výssa",
    "lat": "41.5833",
    "lng": "26.5333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "2805",
    "population_proper": "2805"
  },
  {
    "city": "Néa Kíos",
    "lat": "37.5875",
    "lng": "22.7444",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Peloponnísos",
    "capital": "",
    "population": "2778",
    "population_proper": "2778"
  },
  {
    "city": "Kassándreia",
    "lat": "40.0467",
    "lng": "23.4161",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "2775",
    "population_proper": "2775"
  },
  {
    "city": "Kaména Voúrla",
    "lat": "38.7833",
    "lng": "22.7833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "2761",
    "population_proper": "2761"
  },
  {
    "city": "Choristí",
    "lat": "41.1300",
    "lng": "24.2083",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Anatolikí Makedonía kai Thráki",
    "capital": "",
    "population": "2725",
    "population_proper": "2725"
  },
  {
    "city": "Néa Palátia",
    "lat": "38.3167",
    "lng": "23.7833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "2723",
    "population_proper": "2723"
  },
  {
    "city": "Palaiá Fókaia",
    "lat": "37.7167",
    "lng": "23.9500",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Attikí",
    "capital": "",
    "population": "2713",
    "population_proper": "2713"
  },
  {
    "city": "Níkiti",
    "lat": "40.2228",
    "lng": "23.6686",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Kentrikí Makedonía",
    "capital": "minor",
    "population": "2711",
    "population_proper": "2711"
  },
  {
    "city": "Kárpathos",
    "lat": "35.5075",
    "lng": "27.2136",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Notío Aigaío",
    "capital": "minor",
    "population": "2707",
    "population_proper": "2707"
  },
  {
    "city": "Astakós",
    "lat": "38.5333",
    "lng": "21.0833",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Dytikí Elláda",
    "capital": "minor",
    "population": "2696",
    "population_proper": "2696"
  },
  {
    "city": "Spercheiáda",
    "lat": "38.9167",
    "lng": "22.1333",
    "country": "Greece",
    "iso2": "GR",
    "admin_name": "Stereá Elláda",
    "capital": "minor",
    "population": "2691",
    "population_proper": "2691"
  }
]